### ISSUE TITLE
Blue-ish shade on cropped pictures

### ISSUE THREAD

**Issue by rakemen** [leblancfg/autocrop#100]
Using windows ten, and running the autocrop command via the terminal and my output folder shows a blue-ish version of the cropped pic. Any ideas on how to troubleshoot?

![image](https://user-images.githubusercontent.com/6099915/78166049-d9a3cc00-7469-11ea-9257-d2242a04d4a1.png)

**Comment by leblancfg** [comment]
Geez, I really needed to test that module outside the tests I'd written. Sorry about the bad experience going in :( Hope that fixes it for good!

**Comment by rakemen** [comment]
Thank you for the quick fix.

**Comment by newptcai** [comment]
I still got blueish faces on Linux with today's master branch

**Comment by leblancfg** [comment]
This issue is caused by OpenCV reading files in as BGR, and autocrop not converting them back to `RGB`. I thought I had enough tests in place to handle the common edge cases, but I see that's not the case! Operating system should not be important in this case.

@newptcai would you be able to share a file that has this symptom, so I can recreate and fix? Cheers.
