### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '__array_interface__'

### ISSUE THREAD

**Issue by Troublesis** [leblancfg/autocrop#121]
After I installed autocrop. The original Jupiter notebook in the project runs perfectly fine. But when I change the photo to my own image for testing purpose it returns the following error.

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-1d8a93fa1666> in <module>
      1 img_array = c.crop(loc)
----> 2 PIL.Image.fromarray(img_array)

~\AppData\Local\Programs\Python\Python38\lib\site-packages\PIL\Image.py in fromarray(obj, mode)
   2752     .. versionadded:: 1.1.6
   2753     """
-> 2754     arr = obj.__array_interface__
   2755     shape = arr["shape"]
   2756     ndim = len(shape)

AttributeError: 'NoneType' object has no attribute '__array_interface__'
```
![image](https://user-images.githubusercontent.com/40723560/103572441-aa524c00-4f20-11eb-987c-8a58ece1559d.png)

**Comment by IKetchup** [comment]
I have the same error message. Someone knows where this problem come from ?

My code:

```
from PIL import Image
from autocrop import Cropper

cropper = Cropper()

# Get a Numpy array of the cropped image
cropped_array = cropper.crop('SJ 002 0.jpg') # image of a church stained glasses

# Save the cropped image with PIL
cropped_image = Image.fromarray(cropped_array)
cropped_image.save('cropped.png')
```

Error message : Traceback (most recent call last):
  File "D:/Python/PE/sift.py", line 10, in <module>
    cropped_image = Image.fromarray(cropped_array)
  File "D:\conda\lib\site-packages\PIL\Image.py", line 2754, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'

**Comment by DejaVuMan** [comment]
I will note I receive the same error with a python implementation of mine which attempts to take various frames from saved screenshots of a video and attempts to crop them all to a 256x256 format. The majority of my images successfully get cropped, but more than one ends up not being cropped due to the 'NoneType' Attribute error in the following code format:

![image](https://user-images.githubusercontent.com/58810486/112537911-8845c880-8daf-11eb-9890-cdb89ea82c8b.png)

In this specific case, every image file attempted to be read into the program is in a 576x1024 resolution, with 96DPI and 24 bit depth - most of the photos are below 130kB in size.

This is some debug information I was able to get on the photo which always causes a crash in my case:

![image](https://user-images.githubusercontent.com/58810486/112538429-25086600-8db0-11eb-914f-cd9252bef307.png)

An error occurred when attempting to open a file.
Traceback (most recent call last):
  File "E:/Python Projects/autocrop_video/main.py", line 33, in <module>
    class ScreenCrop:
  File "E:/Python Projects/autocrop_video/main.py", line 42, in ScreenCrop
    cropped_image = Image.fromarray(cropped_array)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\PIL\Image.py", line 2754, in fromarray
    arr = obj.__array_interface__
AttributeError: 'NoneType' object has no attribute '__array_interface__'

**Comment by leblancfg** [comment]
The `Cropper` class returns `None` if a face isn't detected. This is what you're seeing. You're then passing it to PIL, who can't do anything with a `None`.

I will update the docs to perform the check. In the meantime, you can fence the call with:

```py
img_array = cropper.crop(img_location)
if img_array:
    img = PIL.Image.fromarray(img_array)
    ...
```
