### ISSUE TITLE
video crop example

### ISSUE THREAD

**Issue by Tortoise17** [leblancfg/autocrop#133]
Is it possible to use this for videos ? Can you guide?

**Comment by AlonDan** [comment]
Thanks for adding this, I've tried few times with -o but I keep getting the same error:
```
Unrecognized option 'o'.
Error splitting the argument list: Option not found
```

I only get this on the video commands, when I try on normal images it works perfectly fine.
--
I also tried it via batch file in a DIFFERENT way (and paths) just because I was curious, probably I do it wrong even here but, the above is when I tried copy past the same example of course:

`ffmpeg -i ./_SOURCE_/video.mp4 -filter:v fps=fps=1/60 ._RESULT_/ffmpeg_%0d.bmp autocrop -i ./_SOURCE_ -o ./_RESULTS_ --extension jpg`

---
I'm not a programmer so it's hard for me to find where I got wrong, please feel free to direct me with a step-by-step fix or correction so I can try again, thanks ahead! :)
