### ISSUE TITLE
didn't work with pyinstaller

### ISSUE THREAD

**Issue by mdluex** [leblancfg/autocrop#143]
it works fine when I run it in a normal py file but when I try to convert my project to exe with pyinstaller the cropping part  just crashing without giving any error message, i hope to find a fix for this
thank you.

**Comment by mdluex** [comment]
I also tried to add the autocrop files to my project directory, and I got the same results as converting the py file to exe

**Comment by leblancfg** [comment]
Hi Mahmoud! I'm almost certain this has to do with the complexities of packaging `opencv`, which `autocrop` wraps.

Can I suggest taking a look at these two threads and investigating?
1. [StackOverflow: using OpenCV with PyInstaller](https://stackoverflow.com/questions/55175419/using-opencv-with-pyinstaller)
2. https://github.com/pyinstaller/pyinstaller/issues/3426

**Comment by leblancfg** [comment]
@mdluex I've since updated autocrop to use `opencv-python-headless`, which was the recommended step in link #2 above. This had already been a request in #128, so it felt like the right thing to do.

Feel free to re-open the issue if you can pinpoint your PyInstaller issues to actual autocrop code, but like I hope I've alluded to in the reply above, please be aware that OpenCV is not the easiest dependency to lug for e.g. packaging. :)

**Comment by mdluex** [comment]
@leblancfg thanks for your support, I have migrated to cx_freeze and its working fine now, thank you
