### ISSUE TITLE
Loss of quality when resizing

### ISSUE THREAD

**Issue by me2beats** [leblancfg/autocrop#36]
Cropped pics are less clear than original ones.

**Comment by leblancfg** [comment]
I assume that this is due to the fact that the cropped images are smaller portions of the original files, resized to fit the width and height requirements. Also, I won't be able to replicate this without your source file and the line you used to crop it.

Please let me know if that is not the case, but will close this in a week otherwise.

**Comment by leblancfg** [comment]
Closing as unable to replicate. @me2beats, do write back at any time and we can re-open this.
