### ISSUE TITLE
autocrop: not found

### ISSUE THREAD

**Issue by ak9250** [leblancfg/autocrop#58]
Hi i am running this on a gcp vm instance and was able to install it using !pip install autocrop but when I do !autocrop it says 
/bin/sh: 1: autocrop: not found
I also tried 
!python3 -m autocrop
which did not work either
then I tried installing it directly and that didnt work either

**Comment by leblancfg** [comment]
Hi @ak9250!

Looking at your issue, is it safe to assume you installed autocrop from inside a Jupyter notebook? There are issues when installing packages with dependencies, [as documented in this post by Jake VanDerPlas](https://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/).

Before we dive into this, I just want to make sure you've tried installing it directly from your VM's terminal? You may need to uninstall the package in order to make this work.

**Comment by ak9250** [comment]
yes it is in a jupyter notebook but the same commands are working in google colab which is also a jupyter notebook on google servers. You can try out the commands here yourself, just take out the existing text in the cells and do !pip install autocrop and then !autocrop and it works https://colab.research.google.com/notebooks/welcome.ipynb

**Comment by leblancfg** [comment]
Hello again!

I need to make sure that the issue you're having **is actually related to autocrop's code**, and not the method with which you've tried to install it. The are subtle differences between Colab and Jupyter.

Autocrop [is regularly tested on blank Ubuntu VMs](https://travis-ci.org/leblancfg/autocrop/jobs/490141524), and the build is currently passing &mdash; for now, this fact would make me believe that your installation method (i.e. from Jupyter Notebook) is the root cause of your issue.

In your VM, would you be able to install it from the terminal, and report back? Thanks.

You can even start a terminal directly from Jupyter:
![Starting a terminal from Jupyter](https://qiita-image-store.s3.amazonaws.com/0/75594/baaf52d2-d1c2-8bdb-a385-1328ec6f53cb.png)

**Comment by ak9250** [comment]
@leblancfg I believe gcp instances are debian vms, these are the ones i am using https://cloud.google.com/deep-learning-vm/docs/quickstart-cli
also It works for pytorch-latest-gpu for image family but when I do tf-latest-gpu I get those errors.

**Comment by leblancfg** [comment]
@ak9250, I need you to do this so I can take a look at it.

1. Connect to your VM's terminal. See picture above if you want to do this from Jupyter
2. In the terminal, type `pip install autocrop`
3. In the terminal, type `autocrop -v`
4. Copy results and post them here

Thank you

**Comment by ak9250** [comment]
@leblancfg see results
![screen shot 2019-02-15 at 12 14 14 pm](https://user-images.githubusercontent.com/6818285/52872741-47345200-311b-11e9-880c-501282962f2c.png)

**Comment by leblancfg** [comment]
Here's what it looks like as a first guess:
1. it's installing autocrop for Python 2.7 &mdash; that much we can see from the results
2. I'm guessing Python 2.7's packages folder is not included in the `$PATH` environment variable, so when you call `autocrop`, it's not finding it. It would also explain why `python3 -m autocrop` fails, because it's only installed for Py2.

A likely solution seems to be:
0. uninstall the 2.7 version with `pip uninstall autocrop`
1. install the Python 3 version with `pip3 install autocrop`
2. try running `autocrop -v` again

**Comment by leblancfg** [comment]
Regardless of the root cause, I think it's safe to say that the issue lies with the way you've setup or are using your machine, and is not due to code that we can change for this package.

Marking this issue as closed.

**Comment by ak9250** [comment]
@leblancfg yes i tried pip3 install autocrop as well originally and that did not work

**Comment by leblancfg** [comment]
Agreed. If you find a solution, please add to the wiki. Thanks, and good luck!

**Comment by ak9250** [comment]
I had a similar problem with another repo when i ran !python3 -m (repo-package) it worked, not sure why its not working here
Installing collected packages: opencv-python, autocrop
Successfully installed autocrop-0.3.1 opencv-python-3.4.5.20
